### ISSUE TITLE
Cannot build python-qprogedit

### ISSUE THREAD

**Issue by smathot** [dschreij/opensesame-conda-recipes#7]
When I try to update `python-qprogedit` to 4.0.2, and build it with:

```
conda build python-qprogedit
```

I receive an error:

![image](https://cloud.githubusercontent.com/assets/594936/16268528/104c0526-388f-11e6-9e83-84b4d99ffeb6.png)

Perhaps this is a Windows issue, although I don't fully understand what happens. If so, could you build it on Mac OS and update?

**Comment by dschreij** [comment]
Hmm that’s weird. I know this is invalid syntax in python 3, because the comma-syntax is no longer allowed. Exceptions objects should be explicitly
imported with _as_:

```
except IOError as e
```

I don’t know why this particularly happens in this case though…

**Comment by dschreij** [comment]
I could build 4.0.2 without problems. It's uploaded to anaconda cloud
